// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  hero: dynamic(() => import("./Hero")),
  industries: dynamic(() => import("./Industries")),
  rich_text: dynamic(() => import("./RichText")),
  services: dynamic(() => import("./Services")),
  testimonials: dynamic(() => import("./Testimonials")),
};
